
const haslo = new Array(35);
haslo[0] = "Bez pracy nie ma kołaczy";
haslo[1] = "Każdy kij ma dwa końce";
haslo[2] = "Nie ma dymu bez ognia";
haslo[3] = "Dwie strony medalu";
haslo[4] = "Karolina to mały kidsik";
haslo[5] = "Lambo to ziomal";
haslo[6] = "Playstation jest najlepsze";
haslo[7] = "Karolinka dziecior";
haslo[8] = "Polska górą";
haslo[9] = "Robert Lewandowski król";
haslo[10] = "Pudzian jest silny";
haslo[11] = "Najman jest słaby";
haslo[12] = "Co to są za czasy";
haslo[13] = "Tammy to super piesek";
haslo[14] = "Ogniem i mieczem";
haslo[15] = "Raz kozie śmierć";
haslo[16] = "Oko za oko";
haslo[17] = "Ekologia to kłamstwo";
haslo[18] = "Papież polak";
haslo[19] = "Jan Paweł Drugi";
haslo[20] = "W marcu jak w garncu";
haslo[21] = "Toyota Celica";
haslo[22] = "Ostra katana";
haslo[23] = "Co dwie głowy to nie jedna";
haslo[24] = "Krzesło do siedzenia";
haslo[25] = "Segregacja śmieci";
haslo[26] = "Czerwone Ferrari";
haslo[27] = "Rudy to złodziej";
haslo[28] = "Łysy też rudy";
haslo[29] = "Iphone do domu";
haslo[30] = "Dron sobie lata";
haslo[31] = "Chojrak tchórzliwy pies";
haslo[32] = "Klan na drzewie";
haslo[33] = "Miecze i sandały";
haslo[34] = "Życie ostre jak maczeta";
function losowe() {
    let j = Math.floor(Math.random) * 35;
    haslo[j];
};